name: Daily Update Process

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
  push:
    branches:
      - credentials-test

jobs:
  update_process:
    runs-on: ubuntu-latest
    environment: Script running environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client gspread_dataframe python-dotenv

    - name: Set up Google Cloud credentials
      run: |
        echo "${{ secrets.CREDENTIALS_GOOGLE_CLOUD }}" > $HOME/credentials.json
        cat $HOME/credentials.json  # Debug: Check if the file is correctly created
      shell: bash

    - name: Verify credentials file existence
      run: |
        ls -la $HOME/credentials.json  # Debug: Ensure the file exists and is readable
      shell: bash

    - name: Run update process
      run: python Continue-Update-Process.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json
