name: Daily Update Process

on:
  workflow_dispatch: 
  schedule:
    - cron: '10 * * * *'

jobs:
  update_process:
    runs-on: ubuntu-latest
    environment: Script running environment  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client gspread_dataframe python-dotenv

    - name: Run update process
      run: python Continue-Update-Process.py
      env:
        GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.CREDENTIALS_GOOGLE_CLOUD }}  # Now using secrets for Google Cloud credentials
        TYPE: ${{ secrets.TYPE }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AUTH_URI: ${{ secrets.AUTH_URI }}
        TOKEN_URI: ${{ secrets.TOKEN_URI }}
        AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
