name: Daily Update Process

on:
  workflow_dispatch: 
  schedule:
    - cron: '10 * * * *' 

jobs:
  update_process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This will be updated to Node.js 20 automatically by GitHub

    - name: Set up Python
      uses: actions/setup-python@v4  # This will be updated to Node.js 20 automatically by GitHub
      with:
        python-version: '3.8'  # Use the appropriate Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client  # Add other dependencies as needed

    - name: Run update process
      run: python Continue-Update-Process.py
