name: Daily Update Process - Google Sheets

on:
  workflow_dispatch:
  push:


jobs:
  update_process_just_GoogleSheets:
    runs-on: ubuntu-latest
    
    environment: Script running environment

    
    steps:
  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client gspread_dataframe python-dotenv

    - name: Set up Google Cloud credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json
        cat $HOME/credentials.json  # Debug: Check if the file is correctly created
      shell: bash


    - name: Verify credentials file existence
      run: |
        ls -la $HOME/credentials.json  # Debug: Ensure the file exists and is readable
      shell: bash

    - name: Upload transformed data to Google Sheets
      run: python save_to_google_sheet.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        TYPE: ${{ secrets.TYPE }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AUTH_URI: ${{ secrets.AUTH_URI }}
        TOKEN_URI: ${{ secrets.TOKEN_URI }}
        AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
        

